### PR TITLE
Specify required Ruby version

### PR DESCRIPTION
**Pull request by nicolasleger**

### CODE REVIEW

**Comment by lsegal** [comment]
What does this fix?

**Comment by nicolasleger** [comment]
To specify the Ruby version for people as used by Rubygems for example at https://rubygems.org/gems/yard

**Comment by lsegal** [comment]
I'm not sure that this actually fixes an existing problem besides adding more metadata. Unfortunately this has side effects that would affect runtime behavior, so it's not just an aesthetic change.

**Comment by lsegal** [comment]
Marking as WontFix. This change introduces an unnecessary new "yard" file and increases the minimum version requirement.

**Pull request closed without merging**
