### PR TITLE
feat: bump jQuery to 3.6.0

### PR DESCRIPTION
**Pull request by trivikr**
# Description

Building on top of https://github.com/lsegal/yard/pull/1358
* The generate API reference can be viewed at [netlify-link-to-be-updated-once-ready]
* The diff between output when `bundle exec rake` is run at [netlify-link-to-be-updated-once-ready]

A new PR would be cut with squashed commits if required.
I cut this PR originally on fork https://github.com/trivikr/yard/pull/1, but it doesn't run GitHub Actions.

# Completed Tasks

- [x] I have read the [Contributing Guide][contrib].
- [ ] The pull request is complete (implemented / written).
- [x] Git commits have been cleaned up (squash WIP / revert commits).
- [ ] I wrote tests and ran `bundle exec rake` locally (if code is attached to PR).

[contrib]: https://github.com/lsegal/yard/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by trivikr** [comment]
@lsegal Can you approve workflow to run GitHub actions for this WIP PR?
It would help me to get it into ready state.

**Comment by MSP-Greg** [comment]
@trivikr

You should be able to turn on Actions in your fork.  I might be mistaken, but I think an owner/maintainer needs to approve CI runs for **every change** to a PR by a new committer...

**Comment by trivikr** [comment]
> I might be mistaken, but I think an owner/maintainer needs to approve CI runs for every change to a PR by a new committer...

Nope. The maintainer has to approve CI runs [only for first time users](https://github.blog/changelog/2021-04-22-github-actions-maintainers-must-approve-first-time-contributor-workflow-runs/).
This has been done to combat bad actors.

> You should be able to turn on Actions in your fork.

Do you know how this can be done?
I verified in my fork that Actions permissions are ["Allow all actions"](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/disabling-or-limiting-github-actions-for-a-repository#managing-github-actions-permissions-for-your-repository) by default.

**Comment by trivikr** [comment]
Closing this PR as:
* The final PR with squashed commits is posted at https://github.com/lsegal/yard/pull/1397
* I'll try to enable Actions on fork https://github.com/trivikr/yard/pull/1

**Comment by trivikr** [comment]
> > You should be able to turn on Actions in your fork.
> 
> Do you know how this can be done?
> I verified in my fork that Actions permissions are ["Allow all actions"](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/disabling-or-limiting-github-actions-for-a-repository#managing-github-actions-permissions-for-your-repository) by default.

Looks like GitHub disables running workflows on fork by default.
I'd to enable them by visiting https://github.com/trivikr/yard/actions

<details>
<summary>Screenshot</summary>

Screen Shot 2021-08-31 at 1 38 56 PM

</details>

**Pull request closed without merging**
