### PR TITLE
index page, items in 'File Listing' wrapping

### PR DESCRIPTION
**Pull request by MSP-Greg**
Items will break and wrap on spaces in the title.  This change fixes that...

### CODE REVIEW

**Comment by lsegal** [comment]
This is old, but if you still want this merged in, please squash commits. Don't need reverts on a single line of code change.

**Comment by MSP-Greg** [comment]
Sorry

I need to read up on Git, especially merge vs squash.  I've been using the Windows Git client, most of Git's help seems to be based on command line use.  Meanwhile, I'm trying to not get too frustrated with (old) rdoc formatting...

**Comment by lsegal** [comment]
I couldn't resolve this merge myself. Maybe just re-open a clean PR?

**Comment by MSP-Greg** [comment]
Yes, I'll prepare one...

**Comment by lsegal** [comment]
Closing for #984

**Pull request closed without merging**
