### PR TITLE
CI: Drop defunct sudo: false Travis directive

### PR DESCRIPTION
**Pull request by olleolleolle**
# Description

Travis retired a directive. This removes it from the CI config.

See [more at the Travis blog](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).

# Completed Tasks

- [x] I have read the [Contributing Guide][contrib].
- [x] The pull request is complete (implemented / written).
- [x] Git commits have been cleaned up (squash WIP / revert commits).
- [ ] I wrote tests and ran `bundle exec rake` locally (if code is attached to PR).

[contrib]: https://github.com/lsegal/yard/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by olleolleolle** [comment]
Ah, there are overlaps between GitHub Actions workflows and the Travis CI matrix!

Travis could drop the Ruby 2.4-2.7 matrix members!

**Comment by lsegal** [comment]
Travis is _mostly_ legacy anyway, we're just using it as a backup. GitHub is where most of our supported versions are being tested, and if we need to add <2.4 we could spin them up on Actions rather than Travis.

**Comment by lsegal** [comment]
Thank you very much for this improvement!

**Comment by olleolleolle** [comment]
Thank _you_ for keeping Yard alive!

**Pull request merged**
