### PR TITLE
Image assets not rendering in server on windows

### PR DESCRIPTION
**Pull request by MSP-Greg**
Looked into 'asset' images that display fine in doc but not server.  Also, on windows.

Single line change seems to solve the problem

Happy Holidays!

### CODE REVIEW

**Comment by MSP-Greg** [comment]
Okay, now that I took break...

Replace with

render IO.binread(filename)

**Comment by MSP-Greg** [comment]
Cool.  On windows, using server

render File.read(filename) does not work.  Replacing with

render File.read_binary(filename)  does work.  New pull request?

**Comment by lsegal** [comment]
You should just be able to update this one.

**Comment by lsegal** [comment]
Thanks!

**Pull request merged**
