### PR TITLE
Minor Updates to Readme

### PR DESCRIPTION
**Pull request by olbrich**
* made some badges use https
* reflowed some sections
* updated copyright to 2020

# Description

Describe your pull request and problem statement here.

# Completed Tasks

* [x] I have read the [Contributing Guide][contrib].
* [x] The pull request is complete (implemented / written).
* [x] Git commits have been cleaned up (squash WIP / revert commits).
* [x] I wrote tests and ran `bundle exec rake` locally (if code is attached to PR).

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by olbrich** [comment]
@lsegal any idea why these tests failed?  The output isn't useful and I have no way to kick them off again, AFAIK?

**Comment by MSP-Greg** [comment]
@olbrich

> any idea why these tests failed?

I work a fair bit with Actions CI, and I've seen that kind of failure recently.  Not very helpful.  Anyway, I think there's been a commit after this PR was submitted, so you can rebase...

**Comment by olbrich** [comment]
@lsegal any additional feedback?

**Comment by lsegal** [comment]
This looks great, thanks for the PR, sorry about the delay!

**Pull request merged**
