### PR TITLE
Add ruby-head to .travis.yml

### PR DESCRIPTION
**Pull request by aycabta**
# Description

It's important for tests because [YARD uses Ripper for parsing Ruby code](https://github.com/lsegal/yard/blob/7748eda4b96817b0b9ebd7efffbd32d510829393/lib/yard/parser/ruby/ruby_parser.rb#L27) and Ripper is sometimes updated. For your action, [RDoc is tested on ruby-head](https://github.com/ruby/rdoc/blob/eba6eb0c70d0c9a427984ae701e11e5f5340603a/.travis.yml) because [RDoc is using Ripper](https://github.com/ruby/rdoc/blob/224d4428f105193e566fe154b51f507da7c11252/lib/rdoc/parser/ripper_state_lex.rb#L26) now too.

# Completed Tasks

* [x] I have read the [Contributing Guide][contrib].
* [x] The pull request is complete (implemented / written).
* [x] Git commits have been cleaned up (squash WIP / revert commits).
* [x] I wrote tests and ran `bundle exec rake` locally (if code is attached to PR).

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by aycabta** [comment]
Oh, OK, I'll fix tests of YARD for Ruby trunk later. Recent several months, Ripper has many commits.

**Comment by lsegal** [comment]
Seems like there are regressions in ripper that Ruby core should be aware of here.

**Comment by aycabta** [comment]
I created this Pull Request just after I read [#14126 on Ruby trunk (ruby-core:83864)](https://bugs.ruby-lang.org/issues/14126) what is closed at [revision 60892](https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/60892). I made sure of that revision 60891 is failed and revision 60892 is correct on Yard. The cause of tests failure of Pull Request is the revision of ruby-head on Travis CI was delayed. So, please rebuild the tests on Travis CI. [My branch is correct after ruby-head revision is updated](https://travis-ci.org/aycabta/yard/builds/306563863).

**Comment by aycabta** [comment]
Note: This is *not* for latest Ripper behavior. This is for determining if YARD follows latest Ripper's behavior because of [Ripper sometimes changes the behavior](https://bugs.ruby-lang.org/issues/13686). I'm discussing some changes to Ripper with Ruby core team, so I guess this is important.

**Comment by lsegal** [comment]
I agree that this is important. I do hope that backward compatibility is kept in mind though. Ripper can add things, but plenty of things rely on its current behavior, and any type of changes should be backwards compatible, especially since the library is part of core.

Thank you for improving Ripper!

**Comment by aycabta** [comment]
I understand your concerns. I think so that backward compatibility is so important because I'm RDoc 6 main maintainer that uses Ripper, so I treasure backward compatibility of core libraries too. Thank you for your mind, I promise that I pay attention to it.

**Pull request merged**
