### PR TITLE
ci.yml - add Ruby 2.2 & 2.3, update, split windows

### PR DESCRIPTION
**Pull request by MSP-Greg**
# Description

Actions CI changes

1. Added Ruby 2.2 & 2.3
2. Updated macOS & Ubuntu action
3. Split Windows and use action for build tools activation
4. Removed RubyGems & Bundler update code. Actions code installs both

# Completed Tasks

* [x] I have read the [Contributing Guide][contrib].
* [x] The pull request is complete (implemented / written).
* [x] Git commits have been cleaned up (squash WIP / revert commits).
* [ ] I wrote tests and ran `bundle exec rake` locally (if code is attached to PR).

[contrib]: https://github.com/lsegal/yard/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by skalee** [comment]
@lsegal This is very much worth merging, really.

**Comment by lsegal** [comment]
I guess I'm just not sure what the purpose of the Windows specific build configuration is given that the existing config already runs on Windows.

**Comment by MSP-Greg** [comment]
The workflow file should probably be updated.

1. eregon/use-ruby-action@master is outdated.  It has been replaced by ruby/setup-ruby.

2. Due to C19, Actions has put off adding MSYS2 to their images, so they have a rather old set of Windows build tools.  Several of the markup gems are extension gems, so...

3. MSP-Greg/setup-ruby-pkgs uses ruby/setup-ruby for install, and also allows updating build tools, package installation, etc.  It's used by several repos.

I've combined the jobs.

**Comment by MSP-Greg** [comment]
Closing in favor of PR #1384

**Pull request closed without merging**
