### PR TITLE
Extract method parameter names from C function signatures

### PR DESCRIPTION
**Pull request by alexdowad**
Use a couple of regexes on the source for a Ruby method defined in a C extension, to get the parameters. This is already done for methods defined in Ruby, but for those defined in C.

This is not foolproof -- for example, if the Ruby method implemented by a C function takes a block argument, we can't identify that from the C function signature. But at least we can identify regular method arguments.

This makes the generated documentation for C extension methods noticeably better.

### CODE REVIEW

**Comment by alexdowad** [comment]
Just adjusted the regexes to work in Ruby 1.8.7.

**Comment by alexdowad** [comment]
Just added another little tweak (cleanup of a regex) to this PR... please have a look.

**Comment by alexdowad** [comment]
I removed the regex tweak as requested.

**Comment by alexdowad** [comment]
Ping...

**Comment by lsegal** [comment]
Much better, thanks @alexdowad!

**Comment by alexdowad** [comment]
Thanks to you for providing such a great tool, and please let me know how I can make my other PRs better as well.

**Pull request merged**
